name: build

# trigger on any push
# but not on master or tag
on:
  push:
    tags-ignore:
      - "**"
    branches:
      - "**"
      - "!master"

env:
  IMAGE_NAME: "zenika/terraform-aws-cli"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Lint Dockerfile
        uses: brpaz/hadolint-action@master
        with:
          dockerfile: "Dockerfile"

  build:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build image
        run: docker image build . --file Dockerfile --tag $IMAGE_NAME:${GITHUB_REF##*/}

      - name: save image
        run: docker image save -o image.tar $IMAGE_NAME:${GITHUB_REF##*/}

      - name: Upload image artifact
        uses: actions/upload-artifact@v2
        with:
          name: image
          path: image.tar
