name: push-latest

# trigger on master
on:
  push:
    branches:
      - "master"

env:
  IMAGE_NAME: "zenika/terraform-aws-cli"
  IMAGE_TAG: "latest"


jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Lint Dockerfile
        uses: brpaz/hadolint-action@master
        with:
          dockerfile: "Dockerfile"

  build:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build image
        run: docker image build . --file Dockerfile --tag $IMAGE_NAME:IMAGE_TAG

      - name: save image
        run: docker image save -o image.tar $IMAGE_NAME:IMAGE_TAG

      - name: Upload image artifact
        uses: actions/upload-artifact@v2
        with:
          name: image
          path: image.tar

  push:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: download image artifact
        uses: actions/download-artifact@v2
        with:
          name: image

      - name: load image
        run: docker image load --input image.tar

      - name: Login to Docker Hub registry
        run: echo ${{ secrets.DOCKERHUB_PASS }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push image to registry
        run: docker push $IMAGE_NAME:$IMAGE_TAG
