name: release

# trigger on published release
on:
  release:
    types: [published]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Lint Dockerfile
        uses: brpaz/hadolint-action@master
        with:
          dockerfile: "Dockerfile"

  build_push_release:
    runs-on: ubuntu-latest
    needs: lint

    strategy:
      matrix:
        tf_version:
          - "0.11.14"
          - "0.12.29"
          - "0.13.1"
        awscli_version:
          - "1.16.314"
          - "1.17.17"
          - "1.18.127"

    env:
      ORGANIZATION: "zenika"
      IMAGE_NAME: "terraform-aws-cli"

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Get and save the release tag
        run: echo "::set-env name=RELEASE_TAG::${GITHUB_REF##*/}"

      - name: Build and save the image release tag
        run: echo "::set-env name=IMAGE_TAG::release-${RELEASE_TAG}_terraform-${{ matrix.tf_version }}_awscli-${{ matrix.awscli_version }}"

      - name: Build image
        run: docker image build . --file Dockerfile --build-arg TERRAFORM_VERSION=${{ matrix.tf_version }} --build-arg AWS_CLI_VERSION=${{ matrix.awscli_version }} --tag ${ORGANIZATION}/${IMAGE_NAME}:${IMAGE_TAG}

      - name: Login to Docker Hub registry
        run: echo '${{ secrets.DOCKERHUB_PASS }}' | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push image to registry
        run: docker push ${ORGANIZATION}/${IMAGE_NAME}:${IMAGE_TAG}

      - name: Save image
        run: docker image save -o ${IMAGE_NAME}-${IMAGE_TAG}.tar ${ORGANIZATION}/${IMAGE_NAME}:${IMAGE_TAG}

      - name: Upload image artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.IMAGE_NAME }}-${{ env.IMAGE_TAG }}
          path: ${{ env.IMAGE_NAME }}-${{ env.IMAGE_TAG }}.tar
